/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Checks a text for slurs and determines the level of profanity of this, levels go from 0 to 3 */
export function checkText(text: string, maxLevel?: number | undefined | null): boolean
